### ISSUE TITLE
Error when using MSI Installer when Elasticsearch is not installed on same volume

### ISSUE THREAD

**Issue by Budman17r** [elastic/windows-installers#103]
This causes the installation to fail with plugins. 
x-pack
Moving existing plugin directory from D:\Elastic\Elasticsearch\plugins to C:\Users\xxxxxxxxx\AppData\Local\Temp\Elasticsearch 5.6.0\plugins
System.IO.IOException: Source and destination path must have identical roots. Move will not work across volumes.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at System.IO.Abstractions.DirectoryInfoWrapper.MoveTo(String destDirName)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.PreserveInstallTask.MoveCurrentPlugins()
   at Elastic.InstallerHosts.Elasticsearch.Tasks.PreserveInstallTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPreserveInstallAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

**Comment by Budman17r** [comment]
Deleting the plugins directory allows the upgrade to complete. 

Then I had to manually reinstall the plugin.

**Comment by russcam** [comment]
Thanks for opening @Budman17r.  

> 
> Deleting the plugins directory allows the upgrade to complete.
> 
> Then I had to manually reinstall the plugin.

That's the workaround for the moment.
