### ISSUE TITLE
error installing 5.6.3 SQL plugin

### ISSUE THREAD

**Issue by kosckosc** [elastic/windows-installers#134]
Hi

I installed 5.6.3 Elasticsearchh on my linux box:

```
{
"name": "virtual1",
"cluster_name": "Virtual1",
"cluster_uuid": "Hdh18FKPTz--J-N29b0tsg",
"version": {
"number": "5.6.3",
"build_hash": "1a2f265",
"build_date": "2017-10-06T20:33:39.012Z",
"build_snapshot": false,
"lucene_version": "6.6.1"
},
"tagline": "You Know, for Search"
}
```

after installing SQL plugin with:
```
/usr/share/elasticsearch#  ./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/5.6.3.0/elasticsearch-sql-5.6.3.0.zip
```

and I got error:

```
Exception in thread "main" java.lang.IllegalArgumentException: plugin [sql] is incompatible with version [5.6.4]; was designed for version [5.6.3]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:501)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

I have v5.6.3 installed but plugin refuses to install saying it's v5.6.4?
any suggestions?

**Comment by kosckosc** [comment]
after installing node 

> cd site-server
> npm install express --save
> node node-server.js

plugin starts at 8080 port but is unable to connect to elasticsearch
![sql](https://user-images.githubusercontent.com/3097678/32774956-43751f92-c92e-11e7-8247-7f49a625ec28.png)

**Comment by russcam** [comment]
@kosckosc this repository is related to the Windows MSI installer. Since you're running on Linux, this isn't the right place for your issue. I suggest opening a question on https://discuss.elastic.co/c/elasticsearch or perhaps filing an issue on the SQL plugin repository at https://github.com/NLPchina/elasticsearch-sql/

**Comment by kosckosc** [comment]
OK
