### ISSUE TITLE
Error occurred during installaing with SMB plugin Windows MSI

### ISSUE THREAD

**Issue by antimatter96** [elastic/windows-installers#144]
## Elasticsearch version:
5.6.4

## Server OS version:
Windows 8,1, 64Bit

## Original install method (e.g. download page, yum, from source, etc.):
Downloadpage -> elasticsearch-5.6.4.msi

Steps to reproduce:

Start the "elasticsearch-5.6.4.msi", choose the "smb" plugin to install, leave everything else with their default values.
I have attached the Install log file.
[MSI9985d.LOG](https://github.com/elastic/windows-installers/files/1525019/MSI9985d.LOG)

When not choosing the "smb" option the installer installs eleasticsearch with no errors

While scanning through the log I found this one:

```
[0] installing store-smb installing store-smb
The syntax of the command is incorrect.
[0] installing store-smb installing store-smb
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\bin\elasticsearch-plugin.bat install store-smb --batch). ExitCode: 255 ErrorCheck: True ErrorOut:The syntax of the command is incorrect.

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```

**Comment by russcam** [comment]
Thanks for reporting @antimatter96. I don't see this issue locally on Windows 10 or on the integration tests that target Windows Server 2012 R2. It's similar to https://github.com/elastic/windows-installers/issues/75.

Do you have `JAVA_HOME` environment variable set and if so, what does it point to?
