### ISSUE TITLE
6.2.1 BC fails when installing as a Windows Service running under Network Service account

### ISSUE THREAD

**Issue by russcam** [elastic/windows-installers#166]
Running

```
.\build.bat integrate es de65bbc1:6.2.1 *Network*
```

fails to install as a Windows Service running under the Network account. The elasticsearch.log file indicates

```
[2018-02-08T01:19:52,907][WARN ][o.e.b.Natives            ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/win32-x86-64/jnidispatch.dll library: JNA temporary directory '${ES_TMPDIR}' does not exist
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:190) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_92]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_92]
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:104) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:172) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.2.1.jar:6.2.1]
[2018-02-08T01:19:52,925][WARN ][o.e.b.Natives            ] cannot check if running as root because JNA is not available
[2018-02-08T01:19:52,925][WARN ][o.e.b.Natives            ] cannot install system call filter because JNA is not available
[2018-02-08T01:19:52,925][WARN ][o.e.b.Natives            ] cannot register console handler because JNA is not available
[2018-02-08T01:19:52,925][WARN ][o.e.b.JNAKernel32Library ] JNA not found. native methods and handlers will be disabled.
[2018-02-08T01:19:52,925][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2018-02-08T01:19:52,925][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_AS beacuse JNA is not available
[2018-02-08T01:19:52,925][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_FSIZE because JNA is not available
[2018-02-08T01:19:53,166][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: Unable to access 'java.io.tmpdir' (${ES_TMPDIR})
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:299) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:262) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:208) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.2.1.jar:6.2.1]
Caused by: java.nio.file.AccessDeniedException: C:\Windows\system32\${ES_TMPDIR}
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504) ~[?:1.8.0_92]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_92]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_92]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_92]
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:421) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-6.2.1.jar:6.2.1]
	... 12 more
[2018-02-08T01:19:53,166][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [VAGRANT-2012-R2] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'java.io.tmpdir' (${ES_TMPDIR})
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.1.jar:6.2.1]
Caused by: java.lang.IllegalStateException: Unable to access 'java.io.tmpdir' (${ES_TMPDIR})
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:299) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:262) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:208) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.1.jar:6.2.1]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: C:\Windows\system32\${ES_TMPDIR}
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_92]
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504) ~[?:1.8.0_92]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_92]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_92]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_92]
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:421) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:299) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:262) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:208) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.1.jar:6.2.1]
	... 6 more
```

**Comment by russcam** [comment]
Running `elasticsearch.exe` with an administrator account, Elasticsearch starts successfully. Looking at the `bin` directory of the installation

![jna](https://user-images.githubusercontent.com/208231/35952869-2be48a3e-0cd6-11e8-9167-dbee0b467b21.png)

there is a `${ES_TMPDIR}` temp directory there with JNA related artifacts.

**Comment by russcam** [comment]
This also affects 6.2.0.

6.2.0 introduced runtime generated files in the `bin` directory that the account used to run the service may not have access to create in the `bin` directory. In this particular case, the Network Service account does not have write permissions in `bin`.

The workarounds for now are

- not run with Network Service account 

  or 

- grant Network Service account access to the install directory prior to running the installation. 

@Mpdreamz @codebrain Should the account that will run the service should be granted access to write to the install directory as part of installation?

**Comment by JalanshMunshi** [comment]
Hey russcam,

Running it as an administrator solves the problem. Thanks for that.

I am facing the same error when I start elasticsearch on `cmd`. Can you tell me that what actually the problem is and how to solve it?

**Comment by JalanshMunshi** [comment]
Also, when I execute `kibana.bat` on `cmd` in Windows 10 I get an error as follows-

```
C:\Program Files\Elastic\kibana-6.2.1-windows-x86_64\bin>kibana.bat                                                     fs.js:642  
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);                                                                                                                                                                                                                                                                                            

Error: EPERM: operation not permitted, open 'C:\Program Files\Elastic\kibana-6.2.1-windows-x86_64\optimize\.babelcache.json'                                                                                                                        at Error (native)                                                                                                       
at Object.fs.openSync (fs.js:642:18)                                                                                    
at Object.fs.writeFileSync (fs.js:1356:33)                                                                              
at save (C:\Program Files\Elastic\kibana-6.2.1-windows-x86_64\node_modules\babel-register\lib\cache.js:45:16)           
at _combinedTickCallback (internal/process/next_tick.js:73:7)                                                           
at process._tickCallback (internal/process/next_tick.js:104:9)                                                          
at Module.runMain (module.js:606:11)                                                                                    
at run (bootstrap_node.js:383:7)                                                                                        
at startup (bootstrap_node.js:149:9)                                                                                    
at bootstrap_node.js:496:3                                                                                                                                                         
```
Can you help me out?

**Comment by russcam** [comment]
@JalanshMunshi the Kibana Windows Installer is not in a releasable state at present, so hasn't yet been released. As such, I would expect there to be issues with it currently.

**Comment by mrausch** [comment]
I fixed this by manually configuring
`-Djava.io.tmpdir="C:\ProgramData\Elastic\Elasticsearch\${ES_TMPDIR}"`
in `jvm.options` of the ES configuration. Also, my service user has write/modify access to the parent directory.
(using ES 6.2.0)

Smells like a hack though. I guess `${ES_TMPDIR}` should be replaced by a correct env/configuration/whatever variable that works on Windows instead.

**Comment by russcam** [comment]
@mrausch yes, `${ES_TMPDIR}` should be set to `%TMP%\elasticsearch` as part of installation
