### ISSUE TITLE
An error occured during installation

### ISSUE THREAD

**Issue by neerajsaini1982** [elastic/windows-installers#169]
I followed the instructions exactly like mentioned in this web page
https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html

But it ended up with error during installation
uploading log file below.
[MSIf48c7.LOG](https://github.com/elastic/windows-installers/files/1736980/MSIf48c7.LOG)

**Comment by limormerom** [comment]
Same happened to me (on 2 different machines) 
[MSI97a88.LOG](https://github.com/elastic/windows-installers/files/1745367/MSI97a88.LOG)

**Comment by razzul** [comment]
Incorrect **JAVA_HOME**. 
remove /bin from **JAVA_HOME** 
Should be: `C:\ProgramData\Java\jdk1.8.0_131`

**Comment by Mpdreamz** [comment]
```
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
System.TimeoutException: Elasticsearch not seen running after trying for 00:00:30
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.WaitForNodeToAcceptRequests(HttpClient client, String elasticUserPassword)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```

**Comment by Mpdreamz** [comment]
@limormerom 

> Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchPluginsAction.ElasticsearchPlugins
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing x-pack installing x-pack
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co

**Comment by codebrain** [comment]
Closing as OP has not responded.
