### ISSUE TITLE
ElasticSearch failed to run when no plugin is installed. 

### ISSUE THREAD

**Issue by dbclkclk** [elastic/windows-installers#200]
### Environment

Windows 10

### Expected Behaviour
When I run `elasticsearch.exe`, it should fire up the ElasticSearch program. 

### Actual Behaviour

When I run the above command, I get the following error:

```
C:\Program Files\Elastic\Elasticsearch\6.2.4\bin>elasticsearch.exe -E 
[2018-05-29T20:24:48,049][INFO ][o.e.n.Node               ] [MSEDGEWIN10] initializing ...
[2018-05-29T20:24:48,284][INFO ][o.e.e.NodeEnvironment    ] [MSEDGEWIN10] using [1] data paths, mounts [[Windows 10 (C:)]], net usable_space [59.3gb], net total_space [97.6gb], types [NTFS]
[2018-05-29T20:24:48,284][INFO ][o.e.e.NodeEnvironment    ] [MSEDGEWIN10] heap size [1.9gb], compressed ordinary object pointers [true]
[2018-05-29T20:24:48,331][INFO ][o.e.n.Node               ] [MSEDGEWIN10] node name [MSEDGEWIN10], node ID [J5yTqffaR9K43tavP87CIQ]
[2018-05-29T20:24:48,331][INFO ][o.e.n.Node               ] [MSEDGEWIN10] version[6.2.4], pid[6484], build[ccec39f/2018-04-12T20:37:28.497551Z], OS[Windows 10/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_171/25.171-b11]
[2018-05-29T20:24:48,347][INFO ][o.e.n.Node               ] [MSEDGEWIN10] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=${ES_TMPDIR}, -XX:+HeapDumpOnOutOfMemoryError, -Xmx2048m, -Xms2048m, -Delasticsearch, -Des.path.home=C:\Program Files\Elastic\Elasticsearch\6.2.4, -Des.path.conf=C:\ProgramData\Elastic\Elasticsearch\config]
[2018-05-29T20:24:54,377][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [aggs-matrix-stats]
[2018-05-29T20:24:54,377][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [analysis-common]
[2018-05-29T20:24:54,394][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [ingest-common]
[2018-05-29T20:24:54,394][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [lang-expression]
[2018-05-29T20:24:54,394][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [lang-mustache]
[2018-05-29T20:24:54,394][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [lang-painless]
[2018-05-29T20:24:54,394][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [mapper-extras]
[2018-05-29T20:24:54,394][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [parent-join]
[2018-05-29T20:24:54,394][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [percolator]
[2018-05-29T20:24:54,410][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [rank-eval]
[2018-05-29T20:24:54,410][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [reindex]
[2018-05-29T20:24:54,410][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [repository-url]
[2018-05-29T20:24:54,410][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [transport-netty4]
[2018-05-29T20:24:54,410][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] loaded module [tribe]
[2018-05-29T20:24:54,410][INFO ][o.e.p.PluginsService     ] [MSEDGEWIN10] no plugins loaded
[2018-05-29T20:25:03,643][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [MSEDGEWIN10] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.security.authc.accept_default_password] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.4.jar:6.2.4]
Caused by: java.lang.IllegalArgumentException: unknown setting [xpack.security.authc.accept_default_password] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:346) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:310) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:284) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:134) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.node.Node.<init>(Node.java:331) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.4.jar:6.2.4]
        ... 6 more
        Suppressed: java.lang.IllegalArgumentException: unknown secure setting [bootstrap.password] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:346) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:310) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:284) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:134) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.node.Node.<init>(Node.java:331) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
                at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.4.jar:6.2.4]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.4.jar:6.2.4]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.4.jar:6.2.4]
```

### Steps to reproduce the behaviour
1. Run MSI installer
2. select the option to manually start ElasticSearch
 Uncheck all plugins ( do not install any plugins)
3. After installation, go to your command line (administrator mode), navigate to the elasticsearch bin directory and run `elasticsearch.exe`

**Comment by russcam** [comment]
@dbclkclk would you be able to attach the MSI log file for the installation? A log file for the installation process can be found within the `%TEMP%` directory, with a randomly generated name adhering to the format `MSI<random>.LOG`. I'd like to see this log in order to understand what parameters were passed to the installer engine.
