### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by anujj86** [elastic/windows-installers#224]
Steps
Run MSI installer
select the option to manually start ElasticSearch
Uncheck all plugins ( do not install any plugins)
Start installation

![error image](https://user-images.githubusercontent.com/36789992/43881430-cba4b576-9bc9-11e8-87f8-0d7f7400b10d.jpg)

**Installation log**

[installation_log.LOG](https://github.com/elastic/windows-installers/files/2272981/installation_log.LOG)

**Comment by anujj86** [comment]
Can anyone please help me in this.

**Comment by russcam** [comment]
The issue is related to configuring built-in users:

```
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask: Setting up X-Pack passwords
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Elasticsearch is up and running Elasticsearch is up and running
[0] Changing password for 'elastic' Changing password for 'elastic'
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.SetPassword(HttpClient client, String elasticUserPassword, String user, String password)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchSetupXPackPasswordsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

Looking at the elasticsearch log that is included in the MSI log, it looks like the bootstrap password did not match the one in the Elasticsearch keystore, and hence the process of configuring built-in users failed due to inability to authenticate.

Please try the installation again. Please let us know how it goes.

**Comment by codebrain** [comment]
Closing, due to no response.
