### ISSUE TITLE
Msi doesn't work on Win Server 2016

### ISSUE THREAD

**Issue by Neutrino-Sunset** [elastic/windows-installers#228]
### Environment

No

UK

### Expected Behaviour

Install using installer and all defaults the software would run.

### Actual Behaviour

It doesn't run.

### Steps to reproduce the behaviour

Fresh install.

1. Install using installer accepting all defaults. 
2. The install completes successfully.
3. The service does not start. The Windows event log contains exceptions on startup.

```
Application: elasticsearch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Elastic.ProcessHosts.Process.StartupException
   at Elastic.ProcessHosts.Process.ProcessBase.HandleException(System.Exception)
   at System.Reactive.ObserverBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.Observer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.Linq.ObservableImpl.AsObservable`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.AutoDetachObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnErrorCore(System.Exception)
   at System.Reactive.ObserverBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at Elastic.ProcessHosts.Process.ObservableProcess+<>c__DisplayClass22_0.<CreateProcessExitSubscription>b__0(System.Reactive.EventPattern`1<System.Object>)
   at System.Reactive.AnonymousSafeObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)

```

4. Googling suggest to run elasticsearch.exe in an elevated command prompt.
5. Run in cmd as admin.
6. Now it fails because the logging configuration is incorrect.

```
# elasticsearch.exe
[0.003s][error]Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[logging                  ] [] Error opening log file 'logs/gc.log': No such file or directory
```

```
# elasticsearch.exe                                                                   
[Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated i
n version 9.0 and will likely be removed in a future release.                         
0.004s][error][logging                  ] []                                          
```

**Comment by codebrain** [comment]
What version of the MSI are you attempting to install?

**Comment by Neutrino-Sunset** [comment]
6.4.0

**Comment by huw489** [comment]
I hit the same problem.
I believe it's because the log folder for the java virtual machine is missing.

Workaround:  once the install has finished find the install folder e.g. C:\Program Files\Elastic\Elasticsearch\6.4.0  and manually add a "logs" folder here.  The service will then start because it can create the gc log in the logs folder ;-)

**Comment by codebrain** [comment]
Thanks for assisting @huw489, @Neutrino-Sunset would you be able to create the \logs\ folder as suggested above and let me know how you get on?

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
