### ISSUE TITLE
Uninstalling 5.6.3 Fails

### ISSUE THREAD

**Issue by thespatt** [elastic/windows-installers#231]
Hello, 

Have another issue (that's I've seen for a while and never investigated) where trying to uninstall Elasticsearch 5.6.3 from our custom install directory fails.  We install plugins offline if that helps.

Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchValidateArgumentsAction.ElasticsearchValidateArguments
System.Exception: Execution failed (C:\Program Files\Tyler Technologies\Elastic\elasticsearch\bin\elasticsearch-plugin.bat list). ExitCode: 0 ErrorCheck: True ErrorOut: Error: Could not find or load main class Files\Tyler
Caused by: java.lang.ClassNotFoundException: Files\Tyler

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.InstalledPlugins(String installDirectory, String configDirectory)
   at Elastic.Installer.Domain.Model.Base.Plugins.PluginsModelBase`2.Refresh()

**Comment by thespatt** [comment]
Uh oh, I just tried the 6.3.2 MSI hoping to upgrade and it threw the same error
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Immediate.ElasticsearchValidateArgumentsAction.ElasticsearchValidateArguments
System.Exception: Execution failed (C:\Program Files\Tyler Technologies\Elastic\elasticsearch\bin\elasticsearch-plugin.bat list). ExitCode: 0 ErrorCheck: True ErrorOut: Error: Could not find or load main class Files\Tyler
Caused by: java.lang.ClassNotFoundException: Files\Tyler

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.InstalledPlugins(String installDirectory, String configDirectory)
   at Elastic.Installer.Domain.Model.Base.Plugins.PluginsModelBase`2.Refresh()

**Comment by codebrain** [comment]
Would it be possible for you to upload the whole log file please?

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
