### ISSUE TITLE
AN ERROR OCCURRED DURING INSTALLATION

### ISSUE THREAD

**Issue by leejmercer** [elastic/windows-installers#254]
### Environment

 no
 UK

### Steps to reproduce the behaviour ran the msi install file as administrator on windows 10

 Yes
[MSI812dd.LOG](https://github.com/elastic/windows-installers/files/2847793/MSI812dd.LOG)

1.
2.
3.

Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing analysis-icu installing analysis-icu
\Common was unexpected at this time.
[0] installing analysis-icu installing analysis-icu
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.6.0\bin\elasticsearch-plugin.bat install analysis-icu --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Common was unexpected at this time.

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 12:07:38: InstallFinalize. Return value 3.
MSI (s) (DC:F8) [12:07:38:534]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (DC:F8) [12:07:38:534]: User policy value 'DisableRollback' is 0

**Comment by leejmercer** [comment]
Hi,

I ran the msi again this time setting the install, data etc directories to dirs created by myself and it has installed without issue. So all good now thanks

Lee
