### ISSUE TITLE
6.6.1 plugin install: could not find java; set JAVA_HOME or ensure java is in PATH 

### ISSUE THREAD

**Issue by jaipsharma** [elastic/windows-installers#261]
MSI (s) (04:04) [17:04:42:877]: Error in rollback skipped.	Return: 5
MSI (s) (04:04) [17:04:42:877]: Note: 1: 2318 2:  
MSI (s) (04:04) [17:04:42:877]: Calling SRSetRestorePoint API. dwRestorePtType: 13, dwEventType: 103, llSequenceNumber: 29, szDescription: "".
MSI (s) (04:04) [17:04:42:877]: The call to SRSetRestorePoint API succeeded. Returned status: 0.
MSI (s) (04:04) [17:04:42:877]: Unlocking Server
MSI (s) (04:04) [17:04:42:924]: PROPERTY CHANGE: Deleting UpdateStarted property. Its current value is '1'.
Action ended 17:04:42: INSTALL. Return value 3.
Property(S): UpgradeCode = {DAAA2CBA-A1ED-4F29-AFBF-5478617B00F6}
Property(S): INSTALLDIR = C:\Program Files\Elastic\Elasticsearch\6.6.1\
Property(S): DATADIRECTORY = C:\ProgramData\Elastic\Elasticsearch\data
Property(S): CONFIGDIRECTORY = C:\ProgramData\Elastic\Elasticsearch\config
Property(S): LOGSDIRECTORY = C:\ProgramData\Elastic\Elasticsearch\logs
Property(S): NETFRAMEWORK45 = #461308
Property(S): INSTALLDIR.plugins = C:\Program Files\Elastic\Elasticsearch\6.6.1\plugins\
Property(S): INSTALLDIR.bin.xpack = C:\Program Files\Elastic\Elasticsearch\6.6.1\bin\x-pack\
Property(S): INSTALLDIR.bin = C:\Program Files\Elastic\Elasticsearch\6.6.1\bin\
Property(S): INSTALLDIR.bin.x_pack = C:\Program Files\Elastic\Elasticsearch\6.6.1\bin\x-pack\
Property(S): INSTALLDIR.config = C:\Program Files\Elastic\Elasticsearch\6.6.1\config\
Property(S): INSTALLDIR.lib = C:\Program Files\Elastic\Elasticsearch\6.6.1\lib\
Property(S): INSTALLDIR.lib.tools.plugin_cli = C:\Program Files\Elastic\Elasticsearch\6.6.1\lib\tools\plugin-cli\
Property(S): INSTALLDIR.lib.tools.security_cli = C:\Program Files\Elastic\Elasticsearch\6.6.1\lib\tools\security-cli\
Property(S): INSTALLDIR.modules.aggs_matrix_stats = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\aggs-matrix-stats\
Property(S): INSTALLDIR.modules.analysis_common = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\analysis-common\
Property(S): INSTALLDIR.modules.ingest_common = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\ingest-common\
Property(S): INSTALLDIR.modules.lang_expression = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\lang-expression\
Property(S): INSTALLDIR.modules.lang_mustache = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\lang-mustache\
Property(S): INSTALLDIR.modules.lang_painless = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\lang-painless\
Property(S): INSTALLDIR.modules.mapper_extras = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\mapper-extras\
Property(S): INSTALLDIR.modules.parent_join = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\parent-join\
Property(S): INSTALLDIR.modules.percolator = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\percolator\
Property(S): INSTALLDIR.modules.rank_eval = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\rank-eval\
Property(S): INSTALLDIR.modules.reindex = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\reindex\
Property(S): INSTALLDIR.modules.repository_url = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\repository-url\
Property(S): INSTALLDIR.modules.transport_netty4 = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\transport-netty4\
Property(S): INSTALLDIR.modules.tribe = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\tribe\
Property(S): INSTALLDIR.modules.x_pack_ccr = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ccr\
Property(S): INSTALLDIR.modules.x_pack_core = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-core\
Property(S): INSTALLDIR.modules.x_pack_deprecation = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-deprecation\
Property(S): INSTALLDIR.modules.x_pack_graph = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-graph\
Property(S): INSTALLDIR.modules.x_pack_ilm = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ilm\
Property(S): INSTALLDIR.modules.x_pack_logstash = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-logstash\
Property(S): INSTALLDIR.modules.x_pack_ml = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.darwin_x86_64.bin = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\darwin-x86_64\bin\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.darwin_x86_64.lib = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\darwin-x86_64\lib\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.linux_x86_64.bin = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\linux-x86_64\bin\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.linux_x86_64.lib = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\linux-x86_64\lib\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.windows_x86_64.bin = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\windows-x86_64\bin\
Property(S): INSTALLDIR.modules.x_pack_ml.resources = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\resources\
Property(S): INSTALLDIR.modules.x_pack_monitoring = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-monitoring\
Property(S): INSTALLDIR.modules.x_pack_rollup = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-rollup\
Property(S): INSTALLDIR.modules.x_pack_security = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-security\
Property(S): INSTALLDIR.modules.x_pack_sql = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-sql\
Property(S): INSTALLDIR.modules.x_pack_upgrade = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-upgrade\
Property(S): INSTALLDIR.modules.x_pack_watcher = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-watcher\
Property(S): NODENAME = node0
Property(S): Cmd_INSTALLDIR = C:\Program Files\Elastic\Elasticsearch\6.6.1
Property(S): Cmd_DATADIRECTORY = C:\ProgramData\Elastic\Elasticsearch\data
Property(S): Cmd_CONFIGDIRECTORY = C:\ProgramData\Elastic\Elasticsearch\config
Property(S): Cmd_LOGSDIRECTORY = C:\ProgramData\Elastic\Elasticsearch\logs
Property(S): ElasticsearchUninstallDirectoriesAction = **********
Property(S): ElasticsearchRollbackDirectoriesAction = **********
Property(S): ElasticsearchCleanupAction = **********
Property(S): ElasticsearchPreserveInstallAction = **********
Property(S): ElasticsearchDirectoriesAction = **********
Property(S): ElasticsearchConfigurationAction = **********
Property(S): ElasticsearchJvmOptionsAction = **********
Property(S): ElasticsearchPluginsAction = **********
Property(S): ElasticsearchBootstrapPasswordAction = **********
Property(S): ElasticsearchServiceStartTypeAction = **********
Property(S): ElasticsearchSetupXPackPasswordsAction = **********
Property(S): INSTALLDIR.lib.tools = C:\Program Files\Elastic\Elasticsearch\6.6.1\lib\tools\
Property(S): INSTALLDIR.modules = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.darwin_x86_64 = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\darwin-x86_64\
Property(S): INSTALLDIR.modules.x_pack_ml.platform = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.linux_x86_64 = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\linux-x86_64\
Property(S): INSTALLDIR.modules.x_pack_ml.platform.windows_x86_64 = C:\Program Files\Elastic\Elasticsearch\6.6.1\modules\x-pack-ml\platform\windows-x86_64\
Property(S): Product = C:\Program Files\Elastic\Elasticsearch\
Property(S): Elastic = C:\Program Files\Elastic\
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): TARGETDIR = D:\
Property(S): SourceDir = C:\Users\Jxx.xxxxx\Desktop\
Property(S): VersionNT = 603
Property(S): ALLUSERS = 1
Property(S): ElasticProduct = Elasticsearch
Property(S): CurrentVersion = 6.6.1
Property(S): MsiLogging = voicewarmup
Property(S): ARPNOREPAIR = yes
Property(S): ARPNOMODIFY = yes
Property(S): INSTALLASSERVICE = true
Property(S): STARTAFTERINSTALL = true
Property(S): STARTWHENWINDOWSSTARTS = true
Property(S): USELOCALSYSTEM = true
Property(S): USENETWORKSERVICE = false
Property(S): CLUSTERNAME = elasticsearch
Property(S): MASTERNODE = true
Property(S): DATANODE = true
Property(S): INGESTNODE = true
Property(S): LOCKMEMORY = false
Property(S): HTTPPORT = 9200
Property(S): TRANSPORTPORT = 9300
Property(S): ARPHELPLINK = https://discuss.elastic.co/c/elasticsearch
Property(S): ARPPRODUCTICON = app_icon.ico
Property(S): ARPURLINFOABOUT = https://www.elastic.co/products/elasticsearch
Property(S): Manufacturer = Elastic
Property(S): ProductCode = {D72B04B3-82AB-4819-8281-A56E30048DF3}
Property(S): ProductLanguage = 1033
Property(S): ProductName = Elasticsearch 6.6.1
Property(S): ProductVersion = 6.6.1
Property(S): SecureCustomProperties = NETFRAMEWORK45;NEWPRODUCTFOUND;UPGRADEFOUND
Property(S): MsiHiddenProperties = BOOTSTRAPPASSWORD;ElasticsearchBootstrapPasswordAction;ElasticsearchCleanupAction;ElasticsearchConfigurationAction;ElasticsearchDirectoriesAction;ElasticsearchJvmOptionsAction;ElasticsearchPluginsAction;ElasticsearchPreserveInstallAction;ElasticsearchRollbackDirectoriesAction;ElasticsearchServiceStartTypeAction;ElasticsearchSetupXPackPasswordsAction;ElasticsearchUninstallDirectoriesAction;ELASTICUSERPASSWORD;KIBANAUSERPASSWORD;LOGSTASHSYSTEMUSERPASSWORD;PASSWORD;ServicePassword
Property(S): MsiLogFileLocation = C:\Users\Jxx.xxxxx\AppData\Local\Temp\MSI3d96f.LOG
Property(S): PackageCode = {35D9F5E0-8ED7-4C75-B33F-44CFF48E3372}
Property(S): ProductState = -1
Property(S): PackagecodeChanging = 1
Property(S): CURRENTDIRECTORY = C:\Users\Jxx.xxxxx\Desktop
Property(S): CLIENTUILEVEL = 3
Property(S): CLIENTPROCESSID = 12924
Property(S): ACTION = INSTALL
Property(S): USERNAME = Windows User
Property(S): SELECTEDMEMORY = 2048
Property(S): MINIMUMMASTERNODES = 0
Property(S): USEEXISTINGUSER = false
Property(S): XPACKSECURITYENABLED = false
Property(S): SKIPSETTINGPASSWORDS = false
Property(S): XPACKLICENSE = Basic
Property(S): MSICLIENTUSESEMBEDDEDUI = 1
Property(S): MsiSystemRebootPending = 1
Property(S): VersionDatabase = 200
Property(S): VersionMsi = 5.00
Property(S): VersionNT64 = 603
Property(S): WindowsBuild = 9600
Property(S): ServicePackLevel = 0
Property(S): ServicePackLevelMinor = 0
Property(S): MsiNTProductType = 1
Property(S): WindowsFolder = C:\WINDOWS\
Property(S): WindowsVolume = C:\
Property(S): System64Folder = C:\WINDOWS\system32\
Property(S): SystemFolder = C:\WINDOWS\SysWOW64\
Property(S): RemoteAdminTS = 1
Property(S): TempFolder = C:\Users\Jxx.xxxxx\AppData\Local\Temp\
Property(S): ProgramFilesFolder = C:\Program Files (x86)\
Property(S): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(S): CommonFiles64Folder = C:\Program Files\Common Files\
Property(S): AppDataFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\
Property(S): FavoritesFolder = C:\Users\Jxx.xxxxx\Favorites\
Property(S): NetHoodFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(S): PersonalFolder = C:\Users\Jxx.xxxxx\Documents\
Property(S): PrintHoodFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(S): RecentFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\Recent\
Property(S): SendToFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\SendTo\
Property(S): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(S): CommonAppDataFolder = C:\ProgramData\
Property(S): LocalAppDataFolder = C:\Users\Jxx.xxxxx\AppData\Local\
Property(S): MyPicturesFolder = C:\Users\Jxx.xxxxx\Pictures\
Property(S): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(S): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): FontsFolder = C:\WINDOWS\Fonts\
Property(S): GPTSupport = 1
Property(S): OLEAdvtSupport = 1
Property(S): ShellAdvtSupport = 1
Property(S): MsiAMD64 = 6
Property(S): Msix64 = 6
Property(S): Intel = 6
Property(S): PhysicalMemory = 16209
Property(S): VirtualMemory = 12903
Property(S): LogonUser = Jxx.xxxxx
Property(S): UserSID = S-1-5-21-3987594245-2617668953-2445150210-45269
Property(S): UserLanguageID = 16393
Property(S): ComputerName = FA043379
Property(S): SystemLanguageID = 16393
Property(S): ScreenX = 1024
Property(S): ScreenY = 768
Property(S): CaptionHeight = 19
Property(S): BorderTop = 1
Property(S): BorderSide = 1
Property(S): TextHeight = 16
Property(S): TextInternalLeading = 3
Property(S): ColorBits = 32
Property(S): TTCSupport = 1
Property(S): Time = 17:04:43
Property(S): Date = 21-02-2019
Property(S): MsiNetAssemblySupport = 4.7.2556.0
Property(S): MsiWin32AssemblySupport = 6.3.16299.15
Property(S): RedirectedDllSupport = 2
Property(S): AdminUser = 1
Property(S): MsiRunningElevated = 1
Property(S): Privileged = 1
Property(S): DATABASE = C:\WINDOWS\Installer\9a3407.msi
Property(S): OriginalDatabase = C:\Users\Jxx.xxxxx\Desktop\elasticsearch-6.6.1.msi
Property(S): UILevel = 2
Property(S): MsiUIUACOnly = 1
Property(S): ROOTDRIVE = D:\
Property(S): CostingComplete = 1
Property(S): OutOfDiskSpace = 0
Property(S): OutOfNoRbDiskSpace = 0
Property(S): PrimaryVolumeSpaceAvailable = 0
Property(S): PrimaryVolumeSpaceRequired = 0
Property(S): PrimaryVolumeSpaceRemaining = 0
Property(S): INSTALLLEVEL = 1
Property(S): ConfigDirectoryExists = True
Property(S): LogsDirectoryExists = True
Property(S): DataDirectoryExists = True
Property(S): BOOTSTRAPPASSWORD = **********
Property(S): ServiceAccount = .\LocalSystem
Property(S): SOURCEDIR = C:\Users\Jxx.xxxxx\Desktop\
Property(S): SourcedirProduct = {D72B04B3-82AB-4819-8281-A56E30048DF3}
Property(S): ProductToBeRegistered = 1
MSI (s) (04:04) [17:04:43:017]: MainEngineThread is returning 1603
MSI (s) (04:80) [17:04:43:034]: RESTART MANAGER: Session closed.
MSI (s) (04:80) [17:04:43:038]: User policy value 'DisableRollback' is 0
MSI (s) (04:80) [17:04:43:038]: Machine policy value 'DisableRollback' is 0
MSI (s) (04:80) [17:04:43:038]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (04:80) [17:04:43:038]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (04:80) [17:04:43:039]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (04:80) [17:04:43:040]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (04:80) [17:04:43:041]: Destroying RemoteAPI object.
MSI (s) (04:A0) [17:04:43:041]: Custom Action Manager thread ending.
MSI (c) (7C:C0) [17:04:43:042]: Back from server. Return value: 1603
MSI (c) (7C:C0) [17:04:43:042]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
Action ended 17:04:43: INSTALL. Return value 3.
Property(C): UpgradeCode = {DAAA2CBA-A1ED-4F29-AFBF-5478617B00F6}
Property(C): INSTALLDIR = C:\Program Files\Elastic\Elasticsearch\6.6.1
Property(C): DATADIRECTORY = C:\ProgramData\Elastic\Elasticsearch\data
Property(C): CONFIGDIRECTORY = C:\ProgramData\Elastic\Elasticsearch\config
Property(C): LOGSDIRECTORY = C:\ProgramData\Elastic\Elasticsearch\logs
Property(C): NODENAME = node0
Property(C): ProgramFiles64Folder = C:\Program Files\
Property(C): VersionNT = 603
Property(C): ALLUSERS = 1
Property(C): ElasticProduct = Elasticsearch
Property(C): CurrentVersion = 6.6.1
Property(C): MsiLogging = voicewarmup
Property(C): ARPNOREPAIR = yes
Property(C): ARPNOMODIFY = yes
Property(C): INSTALLASSERVICE = true
Property(C): STARTAFTERINSTALL = true
Property(C): STARTWHENWINDOWSSTARTS = true
Property(C): USELOCALSYSTEM = true
Property(C): USENETWORKSERVICE = false
Property(C): CLUSTERNAME = elasticsearch
Property(C): MASTERNODE = true
Property(C): DATANODE = true
Property(C): INGESTNODE = true
Property(C): LOCKMEMORY = false
Property(C): HTTPPORT = 9200
Property(C): TRANSPORTPORT = 9300
Property(C): ARPHELPLINK = https://discuss.elastic.co/c/elasticsearch
Property(C): ARPPRODUCTICON = app_icon.ico
Property(C): ARPURLINFOABOUT = https://www.elastic.co/products/elasticsearch
Property(C): Manufacturer = Elastic
Property(C): ProductCode = {D72B04B3-82AB-4819-8281-A56E30048DF3}
Property(C): ProductLanguage = 1033
Property(C): ProductName = Elasticsearch 6.6.1
Property(C): ProductVersion = 6.6.1
Property(C): SecureCustomProperties = NETFRAMEWORK45;NEWPRODUCTFOUND;UPGRADEFOUND
Property(C): MsiHiddenProperties = BOOTSTRAPPASSWORD;ElasticsearchBootstrapPasswordAction;ElasticsearchCleanupAction;ElasticsearchConfigurationAction;ElasticsearchDirectoriesAction;ElasticsearchJvmOptionsAction;ElasticsearchPluginsAction;ElasticsearchPreserveInstallAction;ElasticsearchRollbackDirectoriesAction;ElasticsearchServiceStartTypeAction;ElasticsearchSetupXPackPasswordsAction;ElasticsearchUninstallDirectoriesAction;ELASTICUSERPASSWORD;KIBANAUSERPASSWORD;LOGSTASHSYSTEMUSERPASSWORD;PASSWORD;ServicePassword
Property(C): MsiLogFileLocation = C:\Users\Jxx.xxxxx\AppData\Local\Temp\MSI3d96f.LOG
Property(C): PackageCode = {35D9F5E0-8ED7-4C75-B33F-44CFF48E3372}
Property(C): ProductState = -1
Property(C): PackagecodeChanging = 1
Property(C): CURRENTDIRECTORY = C:\Users\Jxx.xxxxx\Desktop
Property(C): CLIENTUILEVEL = 3
Property(C): CLIENTPROCESSID = 12924
Property(C): MsiSystemRebootPending = 1
Property(C): VersionDatabase = 200
Property(C): VersionMsi = 5.00
Property(C): ACTION = INSTALL
Property(C): VersionNT64 = 603
Property(C): WindowsBuild = 9600
Property(C): ServicePackLevel = 0
Property(C): ServicePackLevelMinor = 0
Property(C): MsiNTProductType = 1
Property(C): WindowsFolder = C:\WINDOWS\
Property(C): WindowsVolume = C:\
Property(C): System64Folder = C:\WINDOWS\system32\
Property(C): SystemFolder = C:\WINDOWS\SysWOW64\
Property(C): RemoteAdminTS = 1
Property(C): TempFolder = C:\Users\Jxx.xxxxx\AppData\Local\Temp\
Property(C): ProgramFilesFolder = C:\Program Files (x86)\
Property(C): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(C): CommonFiles64Folder = C:\Program Files\Common Files\
Property(C): AppDataFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\
Property(C): FavoritesFolder = C:\Users\Jxx.xxxxx\Favorites\
Property(C): NetHoodFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(C): PersonalFolder = C:\Users\Jxx.xxxxx\Documents\
Property(C): PrintHoodFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(C): RecentFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\Recent\
Property(C): SendToFolder = C:\Users\Jxx.xxxxx\AppData\Roaming\Microsoft\Windows\SendTo\
Property(C): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(C): CommonAppDataFolder = C:\ProgramData\
Property(C): LocalAppDataFolder = C:\Users\Jxx.xxxxx\AppData\Local\
Property(C): MyPicturesFolder = C:\Users\Jxx.xxxxx\Pictures\
Property(C): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(C): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(C): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(C): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(C): DesktopFolder = C:\Users\Public\Desktop\
Property(C): FontsFolder = C:\WINDOWS\Fonts\
Property(C): GPTSupport = 1
Property(C): OLEAdvtSupport = 1
Property(C): ShellAdvtSupport = 1
Property(C): MsiAMD64 = 6
Property(C): Msix64 = 6
Property(C): Intel = 6
Property(C): PhysicalMemory = 16209
Property(C): VirtualMemory = 12934
Property(C): LogonUser = Jxx.xxxxx
Property(C): UserSID = S-1-5-21-3987594245-2617668953-2445150210-45269
Property(C): UserLanguageID = 16393
Property(C): ComputerName = FA043379
Property(C): SystemLanguageID = 16393
Property(C): ScreenX = 1366
Property(C): ScreenY = 768
Property(C): CaptionHeight = 23
Property(C): BorderTop = 1
Property(C): BorderSide = 1
Property(C): TextHeight = 16
Property(C): TextInternalLeading = 3
Property(C): ColorBits = 32
Property(C): TTCSupport = 1
Property(C): Time = 17:04:43
Property(C): Date = 21-02-2019
Property(C): MsiNetAssemblySupport = 4.7.2556.0
Property(C): MsiWin32AssemblySupport = 6.3.16299.15
Property(C): RedirectedDllSupport = 2
Property(C): AdminUser = 1
Property(C): Privileged = 1
Property(C): USERNAME = Windows User
Property(C): DATABASE = C:\Users\Jxx.xxxxx\Desktop\elasticsearch-6.6.1.msi
Property(C): OriginalDatabase = C:\Users\Jxx.xxxxx\Desktop\elasticsearch-6.6.1.msi
Property(C): SELECTEDMEMORY = 2048
Property(C): MINIMUMMASTERNODES = 0
Property(C): USEEXISTINGUSER = false
Property(C): XPACKSECURITYENABLED = false
Property(C): SKIPSETTINGPASSWORDS = false
Property(C): XPACKLICENSE = Basic
Property(C): MSICLIENTUSESEMBEDDEDUI = 1
Property(C): UILevel = 2

**Comment by russcam** [comment]
@jaipsharma please can you attach the entire MSI log as file; the above output is not the entire log. 

Thanks

**Comment by ittchmh** [comment]
Same issue on just installed Server 2019 with latest updates
Full log in attachment
[MSI8212d.LOG](https://github.com/elastic/windows-installers/files/2895171/MSI8212d.LOG)

**Comment by jaipsharma** [comment]
[MSI5559d.LOG](https://github.com/elastic/windows-installers/files/2955198/MSI5559d.LOG)

**Comment by Mpdreamz** [comment]
@jaipsharma it looks like you do not have permissions to install and run a service on your machine:

> MSI (s) (D0:D8) [10:14:36:597]: Product: Elasticsearch 6.6.1 -- Error 1920. Service 'Elasticsearch' (Elasticsearch) failed to start.  Verify that you have sufficient privileges to start system services.

@ittchmh your issue is different:

```
could not find java; set JAVA_HOME or ensure java is in PATH 
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.6.1\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 1 ErrorCheck: True ErrorOut:could not find java; set JAVA_HOME or ensure java is in PATH 

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

Can you verify `JAVA_HOME` was set?

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
