### ISSUE TITLE
An error occured during installation!

### ISSUE THREAD

**Issue by FlyFightCrow** [elastic/windows-installers#267]
MSI Log:
[MSI8b457.LOG](https://github.com/elastic/windows-installers/files/2907302/MSI8b457.LOG)

**Comment by FlyFightCrow** [comment]
I attempted to open the Elasticsearch log file and it wouldn't open to share.

**Comment by piaozhegao** [comment]
This is my install error log

MSI Log:
[Uploading MSI9fae8.LOG…]()

**Comment by Mpdreamz** [comment]
@piaozhegao your error:

```
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing ingest-attachment installing ingest-attachment
\Common은(는) 예상되지 않았습니다.
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.6.1\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Common은(는) 예상되지 않았습니다.

   위치: Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   위치: Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   위치: Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   위치: Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 10:07:46: InstallFinalize. Return value 3.
```

and @FlyFightCrow your error

```
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing analysis-icu installing analysis-icu
\Java\jre1.8.0_152\\bin\java.exe" -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.TempDirectory""` was unexpected at this time.
[0] installing analysis-icu installing analysis-icu
System.Exception: Execution failed (D:\Elastic\6.6.1\bin\elasticsearch-plugin.bat install analysis-icu --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Java\jre1.8.0_152\\bin\java.exe" -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.TempDirectory""` was unexpected at this time.

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

are both the same problem.

This is currently a bug in  Elasticsearch itself see:

https://github.com/elastic/elasticsearch/pull/38624
https://github.com/elastic/elasticsearch/pull/33405

And for our own housekeeping: duplicate of: https://github.com/elastic/windows-installers/issues/252
