### ISSUE TITLE
Elasticsearch 6.7.0 failed to install using MSI

### ISSUE THREAD

**Issue by MohibWasay** [elastic/windows-installers#280]
Failed to install Elasticsearch using MSI installer. Attached with the issue is the log file

![image](https://user-images.githubusercontent.com/6129326/55245315-a9c55580-5264-11e9-92f4-20704ad9d984.png)
[](url)
[MSIad773.log](https://github.com/elastic/windows-installers/files/3023432/MSIad773.log)

**Comment by russcam** [comment]
The screenshot of version 5.5.0  does not align with the log file, which is for version 6.7.0. I'll assume you're installing 6.7.0.

The error is
```
ERROR: Unknown plugin ingest-geoip
[0] installing ingest-geoip installing ingest-geoip
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.7.0\bin\elasticsearch-plugin.bat install ingest-geoip --batch). ExitCode: 64 ErrorCheck: False ErrorOut:
   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

6.7.0 ships with ingest-geoip plugin installed by default, so if you remove that plugin from the list of plugins to install, the installation should succeed.

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
