### ISSUE TITLE
Windows MSI 6.7.1 Installation Fail

### ISSUE THREAD

**Issue by GrandMastaC** [elastic/windows-installers#283]
So I tried to install on a nearly brand new computer with no previous ElasticSearch install and it still failed.  I have no idea what the problem is. I've reviewed the Log file for anything obvious but I'm not an ElasticSearch expert so would appreciate help.

[Elastic Fail Log.txt](https://github.com/elastic/windows-installers/files/3046819/Elastic.Fail.Log.txt)

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by gavinB-orange** [comment]
Just hit exactly the same issue. Possible a problem during ingest-attach install?

```
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing ingest-attachment installing ingest-attachment
warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME
\Common was unexpected at this time.
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.7.1\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Common was unexpected at this time.

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 17:02:51: InstallFinalize. Return value 3.
```

However I tried installing without ingest-attach and got the same error on the next plugin.

I then attempted with no plugins, and that has worked fine.

**Comment by russcam** [comment]
@GrandMastaC, @gavinB-orange where do you have Java installed on the machine? You can get this value with

Command Prompt 
```bat
where java.exe
```

PowerShell
```powershell
where.exe java.exe
```

Also, what is the environment variable `JAVA_HOME` set to? You can get this with

Command Prompt
```bat
echo %JAVA_HOME%
```

PowerShell
```powershell
$env:JAVA_HOME
```

This _looks_ like a quoting issue with the path to Java when calling the plugin install batch file within a process

https://github.com/elastic/windows-installers/blob/421ea616464acf0641b203509b705b5c9d4e2978/src/Installer/Elastic.Installer.Domain/Configuration/Plugin/PluginStateProviderBase.cs#L122-L148

but if you could provide the above details, that would really help in looking into further.

**Comment by kgwood39** [comment]
I have the same problem on Windows 10
where java.exe => C:\ProgramData\Oracle\Java\javapath\java.exe

echo %JAVA_HOME% => C:\Program Files (x86)\Java\jre1.8.0_201\

I checked the %JAVA_HOME% environment variable and noticed that it was for my account, not a system wide variable.  I changed this to a system variable and reinstalled.  It STILL doesn't work.

[MSI9b742.LOG](https://github.com/elastic/windows-installers/files/3074387/MSI9b742.LOG)
[elasticsearch.log](https://github.com/elastic/windows-installers/files/3074390/elasticsearch.log)

**Comment by russcam** [comment]
Related: https://github.com/elastic/elasticsearch/issues/30606 and https://github.com/elastic/elasticsearch/pull/33405

A change in one of the batch files that is invoked when the installer performs plugin installation does not handle parentheses in the `%JAVA_HOME%` environment variable. This has been fixed in later versions.

@GrandMastaC, @kgwood39,  @gavinB-orange: For the version you are looking to install, can you install Java to a path that does not contain parentheses e.g. `C:\Program Files\Java\jre1.8.0_201` (which should be the default 64 bit installation directory), update `%JAVA_HOME%` environment variable to point to this location, and try the installation again? Please report back how the installation goes

**Comment by kgwood39** [comment]
I uninstalled the 32-bit java and installed 64-bit java and updated my %JAVA_HOME%.  I re-downloaded the latest elasticsearch msi installer and attempted to install again.  Unfortunately, I get the same result.
[MSI51088.LOG](https://github.com/elastic/windows-installers/files/3090516/MSI51088.LOG)

**Comment by russcam** [comment]
@kgwood39 It looks like a different issue this time

```
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask: Setting up X-Pack passwords
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Checking Elasticsearch is up and running Checking Elasticsearch is up and running
[0] Elasticsearch is up and running Elasticsearch is up and running
[0] Changing password for 'elastic' Changing password for 'elastic'
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.SetPassword(HttpClient client, String elasticUserPassword, String user, String password)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.SetupXPackPasswordsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```

There was a problem in changing the `elastic` built-in user account. Do you recall the password that you used?

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍

The issue `\Common was unexpected at this time` related to elastic/elasticsearch#30606 and elastic/elasticsearch#33405 has been fixed.
