### ISSUE TITLE
MSI Install error Windows 10

### ISSUE THREAD

**Issue by DEPSTA** [elastic/windows-installers#288]
MSI insstall failed

Install Log file e attached

### Environment
Windows 10
United Kingdom

### Expected Behaviour
MSI install of Elastic V7 on Windows 10
### Actual Behaviour
Install  Failed
### Steps to reproduce the behaviour
N/A

Fresh Install
[MSI806ce_Log.txt](https://github.com/elastic/windows-installers/files/3081921/MSI806ce_Log.txt)

1.
2.
3.

**Comment by russcam** [comment]
It looks like a warning written to stderr during installation of the ingest-attachment plugin caused the failure:

```
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\7.0.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 0 ErrorCheck: True ErrorOut:WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/C:/Program%20Files/Elastic/Elasticsearch/7.0.0/lib/tools/plugin-cli/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```

I would recommend running the installer again _without_ installing the plugin as part of installation, then once the installer successfully installs, install the plugin afterwards, using the command

```bat
C:\Program Files\Elastic\Elasticsearch\7.0.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch
```

Please let me know if this works.

**Comment by DotNet-Ninja** [comment]
I ran into a similar issue on Windows 10 (1809) using the msi installer.
[MSIc0652.LOG](https://github.com/elastic/windows-installers/files/3092180/MSIc0652.LOG)

I believe the issue (in my case was the ingest-geoip plugin). 

`ERROR: Unknown plugin ingest-geoip
[0] installing ingest-geoip installing ingest-geoip
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\7.0.0\bin\elasticsearch-plugin.bat install ingest-geoip --batch). ExitCode: 64 ErrorCheck: False ErrorOut:
   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 20:54:08: InstallFinalize. Return value 3.`

 I will attempt the install without the plugin and report back.

**Comment by willemdh** [comment]
Also had this issue. Installing does work without the plugins.

**Comment by russcam** [comment]
We’re closing this issue due to inactivity; if you’re still in need of resolution, feel free to re-open with the additional details and we'd be glad to help you out 👍
