### ISSUE TITLE
Windows: Elasticsearch 7.2.0 - ${TMPDIR} is not getting created / ERROR: cannot access java.io.tempdir - Installed with Administrator

### ISSUE THREAD

**Issue by andrewjames0304** [elastic/windows-installers#310]
### Expected Behaviour
Elasticsearch service should be running.
### Actual Behaviour
Elasticsearch service is not getting started
### Steps to reproduce the behaviour
Just install the elasticsearch.msi or run elasticsearch-service.bat install from CMD
 Yes, it's a fresh install
Operating System: Windows 8
Error: cannot access java.io.tempdir
Have referenced #18406 and #166. Tried running elasticsearch-x64.exe as an admin, manually created ${TMPDIR} folder and copied the directory address in -Djava.io.tmpdir="" in  jvm.option. Still the service is not getting started. Have tried ZIP installation as well as .MSI installation as well. No go.

**Comment by lansalot** [comment]
I had the same issue. stderr log was showing:

```
2019-07-03 14:41:12 Commons Daemon procrun stderr initialized
java.lang.SecurityException: Security misconfiguration: cannot access java.io.tmpdir
Likely root cause: java.lang.SecurityException: Unable to create temporary file or directory
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:142)
	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
	at java.base/java.nio.file.Files.createTempFile(Files.java:915)
	at org.elasticsearch.bootstrap.Security.selfTest(Security.java:416)
	at org.elasticsearch.bootstrap.Security.configure(Security.java:133)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:216)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
```

I fixed this by running **.\elasticsearch-service manager** and in the GUI, java tab, changing from
`-Djava.io.tmpdir=`
to
`-Djava.io.tmpdir=c:\temp\`

Looks like some environment variable not passing through at service installation, for some reason?

**Comment by andrewjames0304** [comment]
> I had the same issue. stderr log was showing:
> 
> ```
> 2019-07-03 14:41:12 Commons Daemon procrun stderr initialized
> java.lang.SecurityException: Security misconfiguration: cannot access java.io.tmpdir
> Likely root cause: java.lang.SecurityException: Unable to create temporary file or directory
> 	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:142)
> 	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
> 	at java.base/java.nio.file.Files.createTempFile(Files.java:915)
> 	at org.elasticsearch.bootstrap.Security.selfTest(Security.java:416)
> 	at org.elasticsearch.bootstrap.Security.configure(Security.java:133)
> 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:216)
> 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
> 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
> 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
> 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
> 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
> 	at org.elasticsearch.cli.Command.main(Command.java:90)
> 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
> 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
> ```
> 
> I fixed this by running **.\elasticsearch-service manager** and in the GUI, java tab, changing from
> `-Djava.io.tmpdir=`
> to
> `-Djava.io.tmpdir=c:\temp\`
> 
> Looks like some environment variable not passing through at service installation, for some reason?

Ah. Thanks man. It worked!

**Comment by daikakosoma** [comment]
Thank you so much, lansalot!
