### ISSUE TITLE
Plugin install security permissions written to stderr, fail installation

### ISSUE THREAD

**Issue by KaustubhYK** [elastic/windows-installers#311]
Please find installation logs below

[MSI676e0.LOG](https://github.com/elastic/windows-installers/files/3333486/MSI676e0.LOG)

**Comment by ygel** [comment]
It looks like one of the plugins printed a warning and that triggered a failure, @russcam 

```
Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing ingest-attachment installing ingest-attachment
future versions of Elasticsearch will require Java 11; your Java version from  does not meet this requirement
-> Downloading ingest-attachment from elastic
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.sun.java2d.cmm.kcms
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed ingest-attachment
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\7.2.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 0 ErrorCheck: True ErrorOut:future versions of Elasticsearch will require Java 11; your Java version from  does not meet this requirement

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 13:02:33: InstallFinalize. Return value 3.
```

**Comment by ygel** [comment]
@philkra I pinged #ingest group with this

**Comment by russcam** [comment]
@ygel The warning in this instance is an advisory that additional permissions are granted for the plugin to operate. The exit code for the plugin installation is 0, but the installer fails the process because the warning `future versions of Elasticsearch will require Java 11; your Java version from  does not meet this requirement` is written to stderr, which the installer currently deems to be a failure

https://github.com/elastic/windows-installers/blob/0b2cc140b96bae0d411561bdaa7df77bf719b595/src/Installer/Elastic.Installer.Domain/Configuration/Plugin/PluginStateProviderBase.cs#L112-L119

I believe this was initially done because the exit code for plugin install failure was always 0 i.e. exit codes were not propagated back correctly in the batch file. I think this requires re-investigation as it's been a while. We can potentially then rely only on the exit code.

**Comment by russcam** [comment]
I've opened #329 to address
