### ISSUE TITLE
ElasticSearch 7.2 MSI installation fails on Windows 7

### ISSUE THREAD

**Issue by futureshock2038** [elastic/windows-installers#323]
[MSI2cd53.LOG](https://github.com/elastic/windows-installers/files/3428744/MSI2cd53.LOG)

### Environment

Windows 7
Java 8 update 221

### Steps to reproduce the behaviour

1. Fresh install

**Comment by russcam** [comment]
The error is 

```
-> Installed ingest-attachment
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\7.2.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 0 ErrorCheck: True ErrorOut:WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/C:/Program%20Files/Elastic/Elasticsearch/7.2.0/lib/tools/plugin-cli/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 17:01:00: InstallFinalize. Return value 3.
```

This is the same as #311. For now, you can install _without_ installing ingest-attachment plugin, then use the [`elasticsearch-plugin.bat` file](https://www.elastic.co/guide/en/elasticsearch/plugins/current/installation.html) in the install directory `bin` directory to install ingest-attachment plugin afterwards.
