### ISSUE TITLE
An error occured during installation of version 6.7.2 using msi installer. 

### ISSUE THREAD

**Issue by sureshanandhu** [elastic/windows-installers#336]
[MSI6e6d3.LOG](https://github.com/elastic/windows-installers/files/3708364/MSI6e6d3.LOG)
[elasticsearch.log](https://github.com/elastic/windows-installers/files/3708365/elasticsearch.log)

**Comment by ygel** [comment]
Hello @sureshanandhu, thank you for reporting this. 

First, is it possible for you to use latest installer version from https://www.elastic.co/downloads/elasticsearch, currently 7.4.0?

From the MSI logs it seems that installer is trying to overwrite a file in use, error 1603.
```
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\6.7.0\bin\elasticsearch-plugin.bat install repository-s3 --batch). ExitCode: 255 ErrorCheck: True ErrorOut:\Java\jdk-11.0.4\bin\java.exe" -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.TempDirectory""` was unexpected at this time.

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

My only recommendation at this point is to ensure you don't have ES running when you install and use latest version. Let us know how it works out!

`elasticsearch.log` doesn't show anything abnormal. My hunch is that maybe elasticsearch process was running when you ran the installer? Even though times in the MSI logs are in your local time and ES logs seem to be in UTC, they might not overlap.

**Comment by ygel** [comment]
Closing as stale.
