### ISSUE TITLE
MSI installation fails if data/config on different drive to main installation AND error is not shown to end user

### ISSUE THREAD

**Issue by stojy** [elastic/windows-installers#371]
When installing, if a different drive is used for the data/config directories than the main installation, then the installer fails. Also, it fails without providing the reason to the end user.

From the logs..
```
[0] syncing install config directory C:\Program Files\Elastic\Elasticsearch\7.7.0\config with D:\data\ElasticSearch\config. syncing install config directory C:\Program Files\Elastic\Elasticsearch\7.7.0\config with D:\data\ElasticSearch\config.
syncing install config directory C:\Program Files\Elastic\Elasticsearch\7.7.0\config with D:\data\ElasticSearch\config.
moving file: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\elasticsearch.yml to D:\data\ElasticSearch\config\elasticsearch.yml
moving file: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\jvm.options to D:\data\ElasticSearch\config\jvm.options
moving file: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\log4j2.properties to D:\data\ElasticSearch\config\log4j2.properties
moving file: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\roles.yml to D:\data\ElasticSearch\config\roles.yml
moving file: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\role_mapping.yml to D:\data\ElasticSearch\config\role_mapping.yml
moving file: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\users to D:\data\ElasticSearch\config\users
moving file: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\users_roles to D:\data\ElasticSearch\config\users_roles
moving directory: C:\Program Files\Elastic\Elasticsearch\7.7.0\config\jvm.options.d to D:\data\ElasticSearch\config\jvm.options.d
System.IO.IOException: Source and destination path must have identical roots. Move will not work across volumes.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at System.IO.Abstractions.DirectoryWrapper.Move(String sourceDirName, String destDirName)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.CreateDirectoriesTask.CreateConfigDirectory(FileSystemAccessRule rule)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.CreateDirectoriesTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
```

**Comment by reighnman** [comment]
+1 

Issue persists in v7.7.1

`
[0] using existing data directory E:\data using existing data directory E:\data
[0] using existing logs directory E:\logs using existing logs directory E:\logs
[0] syncing install config directory C:\Program Files\Elastic\Elasticsearch\7.7.1\config with E:\config. syncing install config directory C:\Program Files\Elastic\Elasticsearch\7.7.1\config with E:\config.
syncing install config directory C:\Program Files\Elastic\Elasticsearch\7.7.1\config with E:\config.
moving directory: C:\Program Files\Elastic\Elasticsearch\7.7.1\config\jvm.options.d to E:\config\jvm.options.d
System.IO.IOException: Source and destination path must have identical roots. Move will not work across volumes.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at System.IO.Abstractions.DirectoryWrapper.Move(String sourceDirName, String destDirName)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.CreateDirectoriesTask.CreateConfigDirectory(FileSystemAccessRule rule)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.CreateDirectoriesTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchDirectoriesAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 15:19:58: InstallFinalize. Return value 3.
MSI (s) (58:14) [15:19:58:469]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (58:14) [15:19:58:469]: User policy value 'DisableRollback' is 0
MSI (s) (58:14) [15:19:58:469]: Machine policy value 'DisableRollback' is 0
MSI (s) (58:14) [15:19:58:470]: Note: 1: 2318 2:  
`

**Comment by ygel** [comment]
Thank you @reighnman for digging into this, I'll take a look in the next few days.

**Comment by reighnman** [comment]
Thanks @ygel !

Only wrench might be the introduction of jvm.options.d but if it was already being accounted for just a matter of replicating what is being done for plugins.

**Comment by reighnman** [comment]
@ygel #379

**Comment by reighnman** [comment]
Submitted #379, I complied a new msi with this change and was able to upgrade all of my notes from 7.6.2 > 7.8

**Comment by ygel** [comment]
closing with https://github.com/elastic/windows-installers/pull/379
