### ISSUE TITLE
Unable to install Elastic Search in Windows via bat file

### ISSUE THREAD

**Issue by kushalsheth1985** [elastic/windows-installers#390]
Hello, 

I am trying to learn Elastic Search on my office laptop. I have an admin account via which I am trying to install it via bat file. 

While installing I am getting below error - 

C:\Program Files\elasticsearch-7.6.2\bin>.\elasticsearch.bat
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.006s][error][logging] Error opening log file 'logs/gc.log': Permission denied
[0.006s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Could not rename log file 'logs/gc.log' to 'logs/gc.log.05' (Permission denied).
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:123)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)

Kindly help. I did try to install via MSI as well and I am getting some error.. will try to create a new issue rather than clubing it together.

**Comment by ygel** [comment]
Hello @kushalsheth1985, Elasticsearch will try to write its logs in a sibling directory of `bin`. It looks like you're running from `Program Files`, this directory is only writable by elevated processes. Your options are:
- Specify `logs` directory in another user-writable location in the configuration file
- Run `.bat` file from an elevated command prompt
