### ISSUE TITLE
Build failure in with 5.5 snapshot

### ISSUE THREAD

**Issue by rjernst** [elastic/windows-installers#40]
The unified release 5.5 snapshot build failed because the windows installers failed to build. There are two issues here:
* The failure to build
* UR kept going because the installers build command did not exist non zero when there was a failure

https://internal-ci.elastic.co/job/elastic+release-manager+5.5+unified-snapshot/10/consoleFull

**Comment by rjernst** [comment]
Failure output:
```
Created AssemblyInfo file "./src/ProcessHosts/Elastic.ProcessHosts.Elasticsearch/Properties\AssemblyInfo.cs".
Running build failed.
Error:
System.TypeInitializationException: The type initializer for '<StartupCode$FakeLib>.$Fake.MSBuildHelper' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Fake.MSBuildHelper.exactPathOrBinaryOnPath@72-1.Invoke(String input) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 72
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
   at <StartupCode$FakeLib>.$Fake.MSBuildHelper..cctor() in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 110
   --- End of inner exception stack trace ---
   at Fake.MSBuildHelper.get_MSBuildDefaults()
   at Fake.MSBuildHelper.build(FSharpFunc`2 setParams, String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 411
   at Fake.MSBuildHelper.MSBuildWithProjectProperties@473.Invoke(String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 473
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Fake.MSBuildHelper.MSBuildWithProjectProperties(String outputPath, String targets, FSharpFunc`2 properties, IEnumerable`1 projects) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 473
   at Fake.MSBuildHelper.MSBuildRelease(String outputPath, String targets, IEnumerable`1 projects) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 498
   at FSI_0005.Build.Builder.BuildService@87.Invoke(Tuple`2 tupledArg) in C:\Users\vagrant\projects\windows-installers\build\scripts\Build.fsx:line 90
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
   at FSI_0005.Targets.clo@91-27.Invoke(ProductVersions p) in C:\Users\vagrant\projects\windows-installers\build\scripts\Targets.fsx:line 91
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at FSI_0005.Targets.clo@90-26.Invoke(Unit unitVar0) in C:\Users\vagrant\projects\windows-installers\build\scripts\Targets.fsx:line 91
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
System.TypeInitializationException: The type initializer for '<StartupCode$FakeLib>.$Fake.MSBuildHelper' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Fake.MSBuildHelper.exactPathOrBinaryOnPath@72-1.Invoke(String input) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 72
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
   at <StartupCode$FakeLib>.$Fake.MSBuildHelper..cctor() in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 110
   --- End of inner exception stack trace ---
   at Fake.MSBuildHelper.get_MSBuildDefaults()
   at Fake.MSBuildHelper.build(FSharpFunc`2 setParams, String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 411
   at Fake.MSBuildHelper.MSBuildWithProjectProperties@473.Invoke(String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 473
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Fake.MSBuildHelper.MSBuildWithProjectProperties(String outputPath, String targets, FSharpFunc`2 properties, IEnumerable`1 projects) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 473
   at Fake.MSBuildHelper.MSBuildRelease(String outputPath, String targets, IEnumerable`1 projects) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 498
   at FSI_0005.Build.Builder.BuildService@87.Invoke(Tuple`2 tupledArg) in C:\Users\vagrant\projects\windows-installers\build\scripts\Build.fsx:line 90
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
   at FSI_0005.Targets.clo@91-27.Invoke(ProductVersions p) in C:\Users\vagrant\projects\windows-installers\build\scripts\Targets.fsx:line 91
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at FSI_0005.Targets.clo@90-26.Invoke(Unit unitVar0) in C:\Users\vagrant\projects\windows-installers\build\scripts\Targets.fsx:line 91
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target          Duration
------          --------
Clean           00:00:00.0042258
BuildServices   Failure
UnzipProducts   00:00:00.5264247
Status:         Failure
PatchGuids      00:00:00.0584045
  1) System.TypeInitializationException: The type initializer for '<StartupCode$FakeLib>.$Fake.MSBuildHelper' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin'.
PruneFiles      00:00:00.0061268
Total:          00:00:00.9383527
---------------------------------------------------------------------
---------------------------------------------------------------------
---------------------------------------------------------------------
---------------------------------------------------------------------
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Fake.MSBuildHelper.exactPathOrBinaryOnPath@72-1.Invoke(String input) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 72
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
   at <StartupCode$FakeLib>.$Fake.MSBuildHelper..cctor() in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 110
   --- End of inner exception stack trace ---
   at Fake.MSBuildHelper.get_MSBuildDefaults()
   at Fake.MSBuildHelper.build(FSharpFunc`2 setParams, String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 411
   at Fake.MSBuildHelper.MSBuildWithProjectProperties@473.Invoke(String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 473
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Fake.MSBuildHelper.MSBuildWithProjectProperties(String outputPath, String targets, FSharpFunc`2 properties, IEnumerable`1 projects) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 473
   at Fake.MSBuildHelper.MSBuildRelease(String outputPath, String targets, IEnumerable`1 projects) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 498
   at FSI_0005.Build.Builder.BuildService@87.Invoke(Tuple`2 tupledArg) in C:\Users\vagrant\projects\windows-installers\build\scripts\Build.fsx:line 90
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
   at FSI_0005.Targets.clo@91-27.Invoke(ProductVersions p) in C:\Users\vagrant\projects\windows-installers\build\scripts\Targets.fsx:line 91
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at FSI_0005.Targets.clo@90-26.Invoke(Unit unitVar0) in C:\Users\vagrant\projects\windows-installers\build\scripts\Targets.fsx:line 91
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
Dynamic assemblies were generated during evaluation of script (tmp749F).
Can not save cache.


    Directory: C:\vagrant\build\snapshot-artifacts


Mode                LastWriteTime     Length Name                              
----                -------------     ------ ----                              
d----         6/14/2017   9:48 PM            windows-installers                


    Directory: C:\vagrant\build\snapshot-artifacts\windows-installers\build\out


Mode                LastWriteTime     Length Name                              
----                -------------     ------ ----                              
d----         6/14/2017   9:48 PM            elasticsearch                     
Copy-Item : Cannot find path 'C:\Users\vagrant\projects\windows-installers\buil
d\out\elasticsearch\elasticsearch-5.5.0-SNAPSHOT.msi' because it does not 
exist.
At C:\vagrant\build\scripts\build_snapshot_windows-installers.ps1:16 char:1
+ Copy-Item build/out/elasticsearch/elasticsearch-5.5.0-SNAPSHOT.msi 
C:/vagrant/bu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\vagran....0-SNAPSHOT.m 
   si:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyI 
   temCommand
 
```

**Comment by russcam** [comment]
The installer build process was unable to find MSBuild 15.0 and the associated tooling needed to build the solution. This implies that one of

1. the provisioning step `configure_dotnet` hasn't run  
2. that the installation of `microsoft-build-tools` has put MSBuild in a different location

I'll take a look at this

**Comment by russcam** [comment]
OK, the vagrant provisioning step `configure_dotnet` failed because chocolatey was unable to install the microsoft-build-tools package:

> ERROR: Running ["C:\Users\vagrant\AppData\Local\Temp\chocolatey\microsoft-build-tools\15.0.26228.0\vs_BuildTools.exe" --quiet --norestart --add Microsoft.VisualStudio.Workload.WebBuildTools ] was not successful. Exit code was '5003'

but the error code is not honoured by vagrant. Looking at a fix now.

**Comment by russcam** [comment]
This has now been resolved with changes in the windows installer build
