### ISSUE TITLE
ElasticSearch 7.11.1 service crash on Windows 2019

### ISSUE THREAD

**Issue by plancked** [elastic/windows-installers#407]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.1

**Plugins installed**: [none]

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): Windows 2019

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**: Start the service from Services manager

7.11.1 installs fine on Windows 2019, but it does not start after installation.
When trying to start the Service, it runs for a bit, and stops after a few seconds

**Provide logs (if relevant)**:

Faulting application name: elasticsearch.exe, version: 7.11.1.0, time stamp: 0x602a80b1
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1518, time stamp: 0xff301d3c
Exception code: 0xe0434352
Fault offset: 0x00000000000396c9
Faulting process id: 0x930
Faulting application start time: 0x01d7064152fb189f
Faulting application path: C:\Program Files\Elastic\Elasticsearch\7.11.1\bin\elasticsearch.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2b90eeb5-eb2a-457f-8967-46c416b938e3
Faulting package full name: 
Faulting package-relative application ID: 

Application: elasticsearch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Elastic.ProcessHosts.Process.StartupException
   at Elastic.ProcessHosts.Process.ProcessBase.HandleException(System.Exception)
   at System.Reactive.ObserverBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.Observer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.Linq.ObservableImpl.AsObservable`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.AutoDetachObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnErrorCore(System.Exception)
   at System.Reactive.ObserverBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at Elastic.ProcessHosts.Process.ObservableProcess+<>c__DisplayClass22_0.<CreateProcessExitSubscription>b__0(System.Reactive.EventPattern`1<System.Object>)
   at System.Reactive.AnonymousSafeObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)

**Comment by plancked** [comment]
> > ```
> > cluster.initial_master_nodes:
> >   - HP
> > ...
> > ```
> 
> Value `HP` for `initial_master_nodes` looks mildly suspicious, does it satisfy requirements outlined in [important settings](https://www.elastic.co/guide/en/elasticsearch/reference/master/important-settings.html#initial_master_nodes):
> 
> > Identify the initial master nodes by their node.name, which defaults to their hostname. Ensure that the value in cluster.initial_master_nodes matches the node.name exactly. If you use a fully-qualified domain name (FQDN) such as master-node-a.example.com for your node names, then you must use the FQDN in this list. Conversely, if node.name is a bare hostname without any trailing qualifiers, you must also omit the trailing qualifiers in cluster.initial_master_nodes.
> 
> EDIT: it does `node.name: HP`

Hi, that is not the actual value of the file. I edited it for privacy reasons.

**Comment by IoannaT** [comment]
Hello,

This incident also happened to me with Elasticsearch 7.10.2.0, MSI installation, running on 64-bit Windows 10. 
Elasticsearch was running fine for more than 3 weeks as a service with a developers' mode configuration:

```
bootstrap.memory_lock: false
cluster.initial_master_nodes:
  - STBGR10
cluster.name: Ioannas_elasticsearch
http.port: 9200
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: STBGR10
path.data: C:\ProgramData\Elastic\Elasticsearch\data
path.logs: C:\ProgramData\Elastic\Elasticsearch\logs
transport.tcp.port: 9300
xpack.license.self_generated.type: basic
xpack.security.enabled: false
```

After a system reboot including software updates - what a surprise for windows - I got the same crash as @plancked . 

The solution was to include the following in my elasticsearch.yml:

```
network.host: <FQDN>
discovery.seed_hosts: 
   - <FQDN>
```

And Elasticsearch is up and running again!

**Comment by ygel** [comment]
Thank you @IoannaT !
