### ISSUE TITLE
Install fails with plugins selected when behind corporate proxy

### ISSUE THREAD

**Issue by zofog** [elastic/windows-installers#61]
The installer should account for the fact that the vast majority of installs take place behind a corporate proxy. Prior to the MSI, I had to manually update the elasticsearch-plugin.bat file to add "-Dhttp.proxyHost=someproxy.mycorporation.com -Dhttp.proxyPort=xxx" etc. to enable the installation of plugins. With the new MSI, the installation will fail if you select any plugins and there is no proxy set.

**Comment by russcam** [comment]
Thanks for reporting @zofog. This sounds like a useful addition to add to the installer

**Comment by zofog** [comment]
It becomes even more problematic when you use the MSI to perform an upgrade. For example, today I used the MSI to upgrade to v5.5.1 and it automatically detected that I had the mapper-size plugin installed. However, because it was an upgrade the MSI wizard did not give me the option to **not** start the windows service when complete. If I leave the plugin selection set, the install will fail and if I uncheck the plugins, the install will complete successfully and then automatically start the Elasticsearch service (minus the required plugins).

**Comment by zofog** [comment]
I'll add one more...

If I specify the java proxy settings in a JAVA_TOOL_OPTIONS environment variable (which works great for the elasticsearch-plugin.bat), then the MSI installer fails completely and dumps the following error to the Windows Event log. 

Application: MsiExec.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
Stack:
   at System.Reactive.Concurrency.AsyncLock.Wait(System.Action)
   at System.Reactive.TailRecursiveSink`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Run>b__0(System.Action)
   at System.Reactive.Concurrency.Scheduler.<Schedule>b__45(System.Action`1<System.Action>, System.Action`1<System.Action`1<System.Action>>)
   at System.Reactive.Concurrency.Scheduler+<>c__DisplayClass50`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeRec1>b__4d(System.__Canon)
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Reactive.Concurrency.IScheduler, Pair`2<System.__Canon,System.Action`2<System.__Canon,System.Action`1<System.__Canon>>>)
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[[System.Reactive.Concurrency.Scheduler+Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](Pair`2<System.__Canon,System.__Canon>, System.Func`3<System.Reactive.Concurrency.IScheduler,Pair`2<System.__Canon,System.__Canon>,System.IDisposable>)
   at System.Reactive.Concurrency.Scheduler.Schedule[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Reactive.Concurrency.IScheduler, System.__Canon, System.Action`2<System.__Canon,System.Action`1<System.__Canon>>)
   at System.Reactive.Concurrency.Scheduler.Schedule(System.Reactive.Concurrency.IScheduler, System.Action`1<System.Action>)
   at System.Reactive.TailRecursiveSink`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.Collections.Generic.IEnumerable`1<System.IObservable`1<System.__Canon>>)
   at System.Reactive.Linq.ObservableImpl.Concat`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Switch`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.IObservable`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Select`2+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.Reactive.Linq.ObservableImpl.Return`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke()
   at System.Reactive.Concurrency.Scheduler.Invoke(System.Reactive.Concurrency.IScheduler, System.Action)
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.Func`3<System.Reactive.Concurrency.IScheduler,System.__Canon,System.IDisposable>)
   at System.Reactive.Concurrency.Scheduler.Schedule(System.Reactive.Concurrency.IScheduler, System.Action)
   at System.Reactive.Linq.ObservableImpl.Return`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run()
   at System.Reactive.Linq.ObservableImpl.Return`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Select`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Switch`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run()
   at System.Reactive.Linq.ObservableImpl.Switch`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Select`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Switch`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run()
   at System.Reactive.Linq.ObservableImpl.Switch`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Where`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Select`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.ObservableExtensions.SubscribeSafe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.IObserver`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.CombineLatest`4+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run()
   at System.Reactive.Linq.ObservableImpl.CombineLatest`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.IObserver`1<System.__Canon>, System.IDisposable, System.Action`1<System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Run(System.Reactive.Concurrency.IScheduler, State<System.__Canon>)
   at System.Reactive.Concurrency.ScheduledItem`2[[System.TimeSpan, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Reactive.Producer`1+State[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].InvokeCore()
   at System.Reactive.Concurrency.CurrentThreadScheduler+Trampoline.Run(System.Reactive.Concurrency.SchedulerQueue`1<System.TimeSpan>)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[[System.Reactive.Producer`1+State[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](State<System.__Canon>, System.TimeSpan, System.Func`3<System.Reactive.Concurrency.IScheduler,State<System.__Canon>,System.IDisposable>)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[[System.Reactive.Producer`1+State[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Reactive.Core, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](State<System.__Canon>, System.Func`3<System.Reactive.Concurrency.IScheduler,State<System.__Canon>,System.IDisposable>)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SubscribeRaw(System.IObserver`1<System.__Canon>, Boolean)
   at System.Reactive.Producer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Subscribe(System.IObserver`1<System.__Canon>)
   at System.ObservableExtensions.Subscribe[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IObservable`1<System.__Canon>, System.Action`1<System.__Canon>)
   at Elastic.Installer.Domain.Model.Elasticsearch.Plugins.PluginsModel..ctor(Elastic.Installer.Domain.Configuration.Plugin.IPluginStateProvider, System.IObservable`1<System.Tuple`3<Boolean,System.String,System.String>>)
   at Elastic.Installer.Domain.Model.Elasticsearch.ElasticsearchInstallationModel..ctor(Elastic.Installer.Domain.Configuration.Wix.IWixStateProvider, Elastic.Configuration.EnvironmentBased.Java.JavaConfiguration, Elastic.Configuration.EnvironmentBased.ElasticsearchEnvironmentConfiguration, Elastic.Installer.Domain.Configuration.Service.IServiceStateProvider, Elastic.Installer.Domain.Configuration.Plugin.IPluginStateProvider, Elastic.Configuration.FileBased.Yaml.ElasticsearchYamlConfiguration, Elastic.Configuration.FileBased.JvmOpts.LocalJvmOptionsConfiguration, Elastic.Installer.Domain.Configuration.Wix.Session.ISession, System.String[])
   at Elastic.Installer.Domain.Model.Elasticsearch.ElasticsearchInstallationModel.Create(Elastic.Installer.Domain.Configuration.Wix.IWixStateProvider, Elastic.Installer.Domain.Configuration.Wix.Session.ISession, System.String[])
   at Elastic.Installer.UI.EmbeddedUI.GetMainWindow(System.String, Elastic.Installer.Domain.Configuration.Wix.IWixStateProvider, Elastic.Installer.Domain.Configuration.Wix.Session.ISession)
   at Elastic.Installer.UI.EmbeddedUI.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
