### ISSUE TITLE
LOCALSYSTEM has no access to a zip installation's data directory

### ISSUE THREAD

**Issue by agoni75** [elastic/windows-installers#68]
I got a problem, when I installed  elesticsearch in windows 10 via elasticsearch 551.msi, I also included all logs.

[MSI75008.txt](https://github.com/elastic/windows-installers/files/1203727/MSI75008.txt)
[elasticsearch.txt](https://github.com/elastic/windows-installers/files/1203728/elasticsearch.txt)

**Comment by Mpdreamz** [comment]
Hi @agoni75 

Was there already an unzipped Elasticsearch installed at `E:\Elastic\Elasticsearch` ? Or was that installed using the 5.5.0 MSI.

Was Elasticsearch running at the beginning of the installation?

**Comment by Mpdreamz** [comment]
This does not look like an update through the MSI:

> MSI (c) (94:28) [09:13:52:822]: APPCOMPAT: no matching ProductCode found in database.

It looks to be pointed at a data directory that was created by a previous unzipped version

> [2017-08-07T09:25:41,786][WARN ][o.e.e.NodeEnvironment    ] [COM-TECH] lock assertion failed
java.nio.file.AccessDeniedException: E:\Elastic\Elasticsearch\data\nodes\0\node.lock
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_40]
	at 

`LOCALSYSTEM` has no rights to open the lock file already there.

**Comment by brandonmichaelhunter** [comment]
Hey just an FYI, what fixed my issue here was that I had to enter in the username that I log into this machine. So I couldn't use the NT User and local user.
