### ISSUE TITLE
MSI Windows install fails with xpack plugin.

### ISSUE THREAD

**Issue by john-jay** [elastic/windows-installers#84]
stack trace:
Elastic.InstallerHosts.Elasticsearch.Tasks.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing x-pack installing x-pack
Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)

**Comment by trinione** [comment]
Same here. Failed to install on Windows 10 with X-Pack. :( Installed successfully without it. Unable to start as a Service though.

**Comment by soernt** [comment]
**Elasticsearch version**:
5.5.2

**Server OS version**:
Windows 10, 64Bit, German

**Original install method (e.g. download page, yum, from source, etc.)**:
Downloadpage -> elasticsearch-5.5.2.msi

**Description of the problem including expected versus actual behavior**:
The setup erorrs

**Steps to reproduce**:
 1. Start the "elasticsearch-5.5.2.msi", choose the "X-Pack" option to install, leave everything else with theire default values.

I attached the Install log file.
[InstallLog.txt](https://github.com/elastic/windows-installers/files/1263712/InstallLog.txt)

**Comment by russcam** [comment]
@john-jay, @trinione, @soernt, do you have network proxy that might be blocking/intercepting downloads to https://artifacts.elastic.co, where plugins are downloaded and installed from?

**Comment by soernt** [comment]
No, I have no proxy configured. I can request that url without any issues.

**Comment by john-jay** [comment]
There is a proxy at my office. To work around the problem, I installed ES without x-pack, and then downloaded the x-pack zip file, and installed it from a local path.

**Comment by russcam** [comment]
@john-jay 5.6.4 and 6.0.0-rc2 onwards have the ability to specify a proxy to use through which to download plugins. Would you like to give either [5.6.4](https://www.elastic.co/downloads/past-releases/elasticsearch-5-6-4) or [6.0.0](https://www.elastic.co/downloads/past-releases/elasticsearch-6-0-0) a try, supplying proxy credentials?

**Comment by russcam** [comment]
@soernt There's not enough information to replicate what the issue is here, beyond the log indicating that there's a syntax error. Would you like to give either [5.6.4](https://www.elastic.co/downloads/past-releases/elasticsearch-5-6-4) or [6.0.0](https://www.elastic.co/downloads/past-releases/elasticsearch-6-0-0) a try with installing x-pack plugin?

**Comment by russcam** [comment]
I'm closing this issue due to inactivity. Feel free to reopen @john-jay or @soernt if there is an update 👍
